/*
* Auth
*/
export const INITIALIZE_AUTH = 'INITIALIZE_AUTH'

/*
* Common
*/

export const SET_TEMPLATE_THEME = 'SET_TEMPLATE_THEME'
export const SET_TOOLBAR_POSITION = 'SET_TOOLBAR_POSITION'

/*
* Templates
*/

// Templates
export const GET_ALL_TEMPLATES = 'GET_ALL_TEMPLATES'
export const CREATE_TEMPLATE = 'CREATE_TEMPLATE'
export const UPDATE_TEMPLATE = 'UPDATE_TEMPLATE'
export const SET_ACTIVE_TEMPLATE = 'SET_ACTIVE_TEMPLATE'
export const LOAD_TEMPLATE = 'LOAD_TEMPLATE'
export const CLEAR_ACTIVE_TEMPLATE = 'CLEAR_ACTIVE_TEMPLATE'

// Sections
export const ADD_SECTION = 'ADD_SECTION'
export const COPY_SECTION = 'COPY_SECTION'
export const UPDATE_SECTION = 'UPDATE_SECTION'
export const DELETE_SECTION = 'DELETE_SECTION'
export const MOVE_SECTIONS = 'MOVE_SECTIONS'

// Questions
export const ADD_QUESTION = 'ADD_QUESTION'
export const UPDATE_QUESTION = 'UPDATE_QUESTION'
export const DELETE_QUESTION = 'DELETE_QUESTION'
export const MOVE_QUESTIONS = 'MOVE_QUESTIONS'

// Options
export const GET_OPTIONS = 'GET_OPTIONS'
export const ADD_OPTION = 'ADD_OPTION'
export const UPDATE_OPTION = 'UPDATE_OPTION'
export const DELETE_OPTION = 'DELETE_OPTION'

// SubQuestions
export const ADD_SUBQUESTION = 'ADD_SUBQUESTION'
export const UPDATE_SUBQUESTION = 'UPDATE_SUBQUESTION'
export const DELETE_SUBQUESTION = 'DELETE_SUBQUESTION'
export const MOVE_SUBQUESTIONS = 'MOVE_SUBQUESTIONS'

// SubQuestions Options
export const ADD_SUBQUESTION_OPTION = 'ADD_SUBQUESTION_OPTION'
export const UPDATE_SUBQUESTION_OPTION = 'UPDATE_SUBQUESTION_OPTION'
export const DELETE_SUBQUESTION_OPTION = 'DELETE_SUBQUESTION_OPTION'

// Conditions
export const UPDATE_CONDITION = 'UPDATE_CONDITION'
export const DELETE_CONDITION = 'DELETE_CONDITION'

/*
* Checklist
*/
